### ISSUE TITLE
FrozenError

### ISSUE THREAD

**Issue by bengalamx** [erniebrodeur/pushover#34]
Recently I am receiving an error when trying to send a message:

**can't modify frozen Excon::Connection**

Is pretty strange cause in other app is working well.

Any idea?

![Captura de Pantalla 2020-01-09 a la(s) 20 32 41](https://user-images.githubusercontent.com/3253845/72120958-2ff7e780-331f-11ea-88e9-2e89d03c2ed8.png)

**Comment by bengalamx** [comment]
By the way, I do receive the notification.

**Comment by erniebrodeur** [comment]
Sorry for sitting on this, I'll take a look, ty for the info.

**Comment by bengalamx** [comment]
Thank you for the great work!

**Comment by ccammilleri** [comment]
I agree this is harmless, but it still generates an error on a successful send. It caused us some confusion as additional logic failed in our function even though messages were still sent.

**Comment by erniebrodeur** [comment]
So I work on this when I have time and desire.   Nobody is paying me and
I'm not obligated to feel bad you had some issues with it.

It seems you managed a work around just fine.

At this point I will not be cutting a new version for such a minor error.

**Comment by jakub-stastny** [comment]
I'm having this issue as well (`FrozenError: can't modify frozen Excon::Connection  when doing `message.push`), but my messages are not being delivered.

**Comment by erniebrodeur** [comment]
So the major reason I haven't fixed this yet is I don't have my dev env setup.

I will get to this soon.

**Comment by erniebrodeur** [comment]
any one of you is welcome to remove the .freeze from the `Excon.new` line and submit a patch too.

**Comment by jakub-stastny** [comment]
Thanks Ernie, I can verify this works 👍

**Comment by miguelpeniche** [comment]
So I downgraded Excon from 0.72.0 to 0.70.0 and is working fine now. @erniebrodeur I agree you had made a great job without being paid, if you have a patreon account we will make sure for sharing some love. cc @ccammilleri can you try it?

**Comment by erniebrodeur** [comment]
@ccammilleri  

https://www.patreon.com/user?u=32489303
